# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration

require 'capybara/rspec'
require_relative '../spec/features/pages/home'
require_relative '../spec/features/pages/select_make'
require_relative '../spec/features/pages/select_model'
require_relative '../spec/features/pages/select_dealership'
require_relative '../spec/features/pages/select_trim'
require_relative '../spec/features/pages/review_details'
require_relative '../spec/features/pages/personal_information'
require_relative '../spec/features/pages/residence'
require_relative '../spec/features/pages/employment_info'
require_relative '../spec/features/pages/identification_info'

Capybara.default_driver = :selenium
Capybara.register_driver :selenium do |app|
  Capybara::Selenium::Driver.new(app, :browser => :firefox)
end

Capybara.run_server = false
Capybara.wait_on_first_by_default = true
Capybara.default_max_wait_time = 15

RSpec.configure do |config|
  config.run_all_when_everything_filtered = true
end
